---
version: "3"
services:
  internet-speed-logger-ui:
    image: ghcr.io/jeffbyrnes/internet-speed-logger
    ports:
      - 3000:3000
    restart: always
    entrypoint:
      - npm
      - run
      - webserver
    volumes:
      - ./config:/data/config
    depends_on:
      - mongo

  internet-speed-logger:
    image: ghcr.io/jeffbyrnes/internet-speed-logger
    depends_on:
      - speedlogger-web
    restart: always
    entrypoint:
      - npm
      - run
      - speedtest
    volumes:
      - ./config:/data/config

  mongo:
    image: mongo:4
    restart: always
    ports:
      - 27017:27107
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=speedtest
      - MONGO_INITDB_DATABASE=speedtest
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # README: Uncomment this stanza to run a container that provides UI access to
  #         the MongoDB server container
  # mongo-express:
  #   image: mongo-express
  #   depends_on:
  #     - mongo
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=speedtest
  #     - ME_CONFIG_OPTIONS_EDITORTHEME=solarized
